import {
    compareEnvironments,
    createProject,
    createServer,
    updateServer,
    deleteServer,
    createSnapshot,
    getProjects,
    getSettings,
    testServer,
    updateSettings,
    listServers,
    listEnvironments,
    createEnvironment,
    assignEnvironmentBinding,
    listEnvironmentBindings,
    updateEnvironment,
    deleteEnvironment,
    updateProject,
    deleteProject,
} from '../services/api';

export function useApi() {
    return {
        getProjects,
        createProject,
        compareEnvironments,
        createSnapshot,
        getSettings,
        updateSettings,
        // servers & environments
        listServers,
        createServer,
        updateServer,
        deleteServer,
        testServer,
        listEnvironments,
        createEnvironment,
        assignEnvironmentBinding,
        listEnvironmentBindings,
        updateEnvironment,
        deleteEnvironment,
        updateProject,
        deleteProject,
    };
}